[node]
# the private spend key of the signer
signer-key = "8bcfad3959892e8334fa287a3c9755fed017cd7a9e8c68d7540dc9e69fa4a00d"
# the period in seconds to check some mint and election kernel opportunities
kernel-operation-period = 700
# the maximum cache size in MB
memory-cache-size = 4096
# how many seconds to keep unconfirmed transactions in the cache storage
# this also limits the confirmed snapshots finalization cache to peer
cache-ttl = 7200

[storage]
# enable badger value log gc will reduce disk storage usage
value-log-gc = true
# max levels should be increased when data too big and badger panic
# increase the level to 8 when data grows big to execeed 16TB
# the max levels can not be decreased once up, so be cautious
max-compaction-levels = 7

[p2p]
# the UDP port for communcation with other nodes
port = 5850
# the seed relayer nodes list
seeds = [
	"06ff8589d5d8b40dd90a8120fa65b273d136ba4896e46ad20d76e53a9b73fd9f@seed.mixin.dev:5850"
]
# a relayer needs a public address to listen and relay messages to other nodes
# a signer should set this value to false for security
relayer = false
# metric different message types sent and received
metric = false

[rpc]
# enable rpc access by setting a valid TCP port number
port = 6860
# whether respond the runtime of each RPC call
runtime = false

[dev]
# enable the pprof web server with a valid TCP port number
port = 7870
